services:
  statistic:
    image: statistic
    networks:
      - my-network
    ports:
      - "5000"
    deploy:
      replicas: 3
    environment:
      - DATABASE_URL=postgresql://user:password@service1_db:5432/database

  news:
    image: news
    networks:
      - my-network
    ports:
      - "5001"
    deploy:
      replicas: 3
    environment:
      - DATABASE_URL=postgres://service2_db

  service1_db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  service2_db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  gateway:
    image: gateway
    container_name: gateway
    networks:
      - my-network
    ports:
      - "3000:3000"

networks:
  my-network:
    driver: bridge