# Use the official Python image
FROM python:3.9

# Set the working directory
WORKDIR /app

# Copy the source code to the container
COPY news.py /app/

# Install the required Python packages
RUN pip install flask-socketio eventlet
RUN pip install Flask-SQLAlchemy
RUN pip install requests
RUN pip install psycopg2-binary
RUN pip install PyJWT

# Expose the port the application runs on
EXPOSE 5001

# Define the command to run the application
CMD ["python", "news.py"]
